//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/GameActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameActions"",
    ""maps"": [
        {
            ""name"": ""InGame"",
            ""id"": ""1ddd219f-30cd-4baa-8e8f-90edbcec54b4"",
            ""actions"": [
                {
                    ""name"": ""MoveCamera"",
                    ""type"": ""Value"",
                    ""id"": ""095c05d6-08ac-473d-911d-c69afd2d4d91"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Build"",
                    ""type"": ""Button"",
                    ""id"": ""3d2e49d8-a3e2-4c8e-9d2b-f0d113fa15ee"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SetLaneWidthTo1"",
                    ""type"": ""Button"",
                    ""id"": ""e3d14fe2-fae1-435b-9de9-6165c6f1406a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SetLaneWidthTo2"",
                    ""type"": ""Button"",
                    ""id"": ""8b939ddd-fa55-4c30-830a-873b653917da"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SetLaneWidthTo3"",
                    ""type"": ""Button"",
                    ""id"": ""d5df3627-5ede-44a8-ae0c-f301de14767a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SaveGame"",
                    ""type"": ""Button"",
                    ""id"": ""ee5f7868-3d5b-4fce-aaae-08b0d5cbd339"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LoadGame"",
                    ""type"": ""Button"",
                    ""id"": ""bdd5d218-0a05-40b7-87bc-f1b845fddf08"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DivideRoad"",
                    ""type"": ""Button"",
                    ""id"": ""887c1d3b-fdc0-480b-b3c5-4e85fd0cdcd5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RemoveRoad"",
                    ""type"": ""Button"",
                    ""id"": ""80942f95-8132-432e-aa8b-38c487f29c31"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AbandonBuild"",
                    ""type"": ""Button"",
                    ""id"": ""f313cc28-09f8-48e3-bbd6-feb27caf5592"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Elevate"",
                    ""type"": ""Button"",
                    ""id"": ""6d5ae660-34f7-4554-8f69-a764e81bdf22"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Lower"",
                    ""type"": ""Button"",
                    ""id"": ""676f582d-b29b-4a4a-8d86-c26f57cdb8e5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DragCamera"",
                    ""type"": ""Button"",
                    ""id"": ""b37da4a0-cfbf-49f6-ac50-c78e369e4621"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleParallelBuildMode"",
                    ""type"": ""Button"",
                    ""id"": ""354b1c2c-d354-4896-bb11-dbcdc1c9205e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7298c412-af08-40c2-9d8d-b43e6400c512"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Build"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""036c33a6-d60f-447e-bb9d-e53f20f46030"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SetLaneWidthTo1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""3D Vector"",
                    ""id"": ""594fff7b-1463-408e-862c-a25d39d2828a"",
                    ""path"": ""3DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveCamera"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d6931a97-9768-44d6-957b-2a0d52e8832d"",
                    ""path"": ""<Mouse>/scroll/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""4527604f-5e27-4046-bc8b-fc853247ef4f"",
                    ""path"": ""<Mouse>/scroll/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""10f23556-59fb-4d57-a3b8-cebe6ce53cee"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""46d719e4-519f-49b3-800d-62740fd55dd6"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""forward"",
                    ""id"": ""bf389f64-2a73-4744-93a6-6ca10e5363d2"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""backward"",
                    ""id"": ""2933f7f8-4d06-4d65-b311-7f1b562201d2"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""994d0935-103d-4fc5-bc6e-c0b24d6fc956"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SetLaneWidthTo2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""20c7840a-7b81-4404-b74c-f921369194b4"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SetLaneWidthTo3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a7904c07-9415-4eb0-9d11-9cd2ac292f15"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SaveGame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3c5d306d-99fa-4663-8bc1-052e630aae2b"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LoadGame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9cf8bcdb-8c9c-4afd-80d2-b9afbb7fafa2"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DivideRoad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""89218214-cf9e-49aa-9d99-a9b8961089e6"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RemoveRoad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cf87bb18-b175-4013-afdc-7869fa33628f"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AbandonBuild"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""69fcf976-c80a-4ba3-a234-88990b533433"",
                    ""path"": ""<Mouse>/forwardButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Elevate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""924d7ac7-d01e-4a80-a91b-29b23a523fe3"",
                    ""path"": ""<Keyboard>/period"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Elevate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e8929b3b-afa8-4bbd-8afc-bf97bc86de06"",
                    ""path"": ""<Mouse>/backButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Lower"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1a6edfec-232e-435d-86b4-1b9530bf7332"",
                    ""path"": ""<Keyboard>/comma"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Lower"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""00a3e5ab-669c-4301-a5fd-f9e13a3f6127"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DragCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""41e7c391-159f-4531-80d9-bcc1ccdc366f"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleParallelBuildMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // InGame
        m_InGame = asset.FindActionMap("InGame", throwIfNotFound: true);
        m_InGame_MoveCamera = m_InGame.FindAction("MoveCamera", throwIfNotFound: true);
        m_InGame_Build = m_InGame.FindAction("Build", throwIfNotFound: true);
        m_InGame_SetLaneWidthTo1 = m_InGame.FindAction("SetLaneWidthTo1", throwIfNotFound: true);
        m_InGame_SetLaneWidthTo2 = m_InGame.FindAction("SetLaneWidthTo2", throwIfNotFound: true);
        m_InGame_SetLaneWidthTo3 = m_InGame.FindAction("SetLaneWidthTo3", throwIfNotFound: true);
        m_InGame_SaveGame = m_InGame.FindAction("SaveGame", throwIfNotFound: true);
        m_InGame_LoadGame = m_InGame.FindAction("LoadGame", throwIfNotFound: true);
        m_InGame_DivideRoad = m_InGame.FindAction("DivideRoad", throwIfNotFound: true);
        m_InGame_RemoveRoad = m_InGame.FindAction("RemoveRoad", throwIfNotFound: true);
        m_InGame_AbandonBuild = m_InGame.FindAction("AbandonBuild", throwIfNotFound: true);
        m_InGame_Elevate = m_InGame.FindAction("Elevate", throwIfNotFound: true);
        m_InGame_Lower = m_InGame.FindAction("Lower", throwIfNotFound: true);
        m_InGame_DragCamera = m_InGame.FindAction("DragCamera", throwIfNotFound: true);
        m_InGame_ToggleParallelBuildMode = m_InGame.FindAction("ToggleParallelBuildMode", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // InGame
    private readonly InputActionMap m_InGame;
    private List<IInGameActions> m_InGameActionsCallbackInterfaces = new List<IInGameActions>();
    private readonly InputAction m_InGame_MoveCamera;
    private readonly InputAction m_InGame_Build;
    private readonly InputAction m_InGame_SetLaneWidthTo1;
    private readonly InputAction m_InGame_SetLaneWidthTo2;
    private readonly InputAction m_InGame_SetLaneWidthTo3;
    private readonly InputAction m_InGame_SaveGame;
    private readonly InputAction m_InGame_LoadGame;
    private readonly InputAction m_InGame_DivideRoad;
    private readonly InputAction m_InGame_RemoveRoad;
    private readonly InputAction m_InGame_AbandonBuild;
    private readonly InputAction m_InGame_Elevate;
    private readonly InputAction m_InGame_Lower;
    private readonly InputAction m_InGame_DragCamera;
    private readonly InputAction m_InGame_ToggleParallelBuildMode;
    public struct InGameActions
    {
        private @GameActions m_Wrapper;
        public InGameActions(@GameActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @MoveCamera => m_Wrapper.m_InGame_MoveCamera;
        public InputAction @Build => m_Wrapper.m_InGame_Build;
        public InputAction @SetLaneWidthTo1 => m_Wrapper.m_InGame_SetLaneWidthTo1;
        public InputAction @SetLaneWidthTo2 => m_Wrapper.m_InGame_SetLaneWidthTo2;
        public InputAction @SetLaneWidthTo3 => m_Wrapper.m_InGame_SetLaneWidthTo3;
        public InputAction @SaveGame => m_Wrapper.m_InGame_SaveGame;
        public InputAction @LoadGame => m_Wrapper.m_InGame_LoadGame;
        public InputAction @DivideRoad => m_Wrapper.m_InGame_DivideRoad;
        public InputAction @RemoveRoad => m_Wrapper.m_InGame_RemoveRoad;
        public InputAction @AbandonBuild => m_Wrapper.m_InGame_AbandonBuild;
        public InputAction @Elevate => m_Wrapper.m_InGame_Elevate;
        public InputAction @Lower => m_Wrapper.m_InGame_Lower;
        public InputAction @DragCamera => m_Wrapper.m_InGame_DragCamera;
        public InputAction @ToggleParallelBuildMode => m_Wrapper.m_InGame_ToggleParallelBuildMode;
        public InputActionMap Get() { return m_Wrapper.m_InGame; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InGameActions set) { return set.Get(); }
        public void AddCallbacks(IInGameActions instance)
        {
            if (instance == null || m_Wrapper.m_InGameActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_InGameActionsCallbackInterfaces.Add(instance);
            @MoveCamera.started += instance.OnMoveCamera;
            @MoveCamera.performed += instance.OnMoveCamera;
            @MoveCamera.canceled += instance.OnMoveCamera;
            @Build.started += instance.OnBuild;
            @Build.performed += instance.OnBuild;
            @Build.canceled += instance.OnBuild;
            @SetLaneWidthTo1.started += instance.OnSetLaneWidthTo1;
            @SetLaneWidthTo1.performed += instance.OnSetLaneWidthTo1;
            @SetLaneWidthTo1.canceled += instance.OnSetLaneWidthTo1;
            @SetLaneWidthTo2.started += instance.OnSetLaneWidthTo2;
            @SetLaneWidthTo2.performed += instance.OnSetLaneWidthTo2;
            @SetLaneWidthTo2.canceled += instance.OnSetLaneWidthTo2;
            @SetLaneWidthTo3.started += instance.OnSetLaneWidthTo3;
            @SetLaneWidthTo3.performed += instance.OnSetLaneWidthTo3;
            @SetLaneWidthTo3.canceled += instance.OnSetLaneWidthTo3;
            @SaveGame.started += instance.OnSaveGame;
            @SaveGame.performed += instance.OnSaveGame;
            @SaveGame.canceled += instance.OnSaveGame;
            @LoadGame.started += instance.OnLoadGame;
            @LoadGame.performed += instance.OnLoadGame;
            @LoadGame.canceled += instance.OnLoadGame;
            @DivideRoad.started += instance.OnDivideRoad;
            @DivideRoad.performed += instance.OnDivideRoad;
            @DivideRoad.canceled += instance.OnDivideRoad;
            @RemoveRoad.started += instance.OnRemoveRoad;
            @RemoveRoad.performed += instance.OnRemoveRoad;
            @RemoveRoad.canceled += instance.OnRemoveRoad;
            @AbandonBuild.started += instance.OnAbandonBuild;
            @AbandonBuild.performed += instance.OnAbandonBuild;
            @AbandonBuild.canceled += instance.OnAbandonBuild;
            @Elevate.started += instance.OnElevate;
            @Elevate.performed += instance.OnElevate;
            @Elevate.canceled += instance.OnElevate;
            @Lower.started += instance.OnLower;
            @Lower.performed += instance.OnLower;
            @Lower.canceled += instance.OnLower;
            @DragCamera.started += instance.OnDragCamera;
            @DragCamera.performed += instance.OnDragCamera;
            @DragCamera.canceled += instance.OnDragCamera;
            @ToggleParallelBuildMode.started += instance.OnToggleParallelBuildMode;
            @ToggleParallelBuildMode.performed += instance.OnToggleParallelBuildMode;
            @ToggleParallelBuildMode.canceled += instance.OnToggleParallelBuildMode;
        }

        private void UnregisterCallbacks(IInGameActions instance)
        {
            @MoveCamera.started -= instance.OnMoveCamera;
            @MoveCamera.performed -= instance.OnMoveCamera;
            @MoveCamera.canceled -= instance.OnMoveCamera;
            @Build.started -= instance.OnBuild;
            @Build.performed -= instance.OnBuild;
            @Build.canceled -= instance.OnBuild;
            @SetLaneWidthTo1.started -= instance.OnSetLaneWidthTo1;
            @SetLaneWidthTo1.performed -= instance.OnSetLaneWidthTo1;
            @SetLaneWidthTo1.canceled -= instance.OnSetLaneWidthTo1;
            @SetLaneWidthTo2.started -= instance.OnSetLaneWidthTo2;
            @SetLaneWidthTo2.performed -= instance.OnSetLaneWidthTo2;
            @SetLaneWidthTo2.canceled -= instance.OnSetLaneWidthTo2;
            @SetLaneWidthTo3.started -= instance.OnSetLaneWidthTo3;
            @SetLaneWidthTo3.performed -= instance.OnSetLaneWidthTo3;
            @SetLaneWidthTo3.canceled -= instance.OnSetLaneWidthTo3;
            @SaveGame.started -= instance.OnSaveGame;
            @SaveGame.performed -= instance.OnSaveGame;
            @SaveGame.canceled -= instance.OnSaveGame;
            @LoadGame.started -= instance.OnLoadGame;
            @LoadGame.performed -= instance.OnLoadGame;
            @LoadGame.canceled -= instance.OnLoadGame;
            @DivideRoad.started -= instance.OnDivideRoad;
            @DivideRoad.performed -= instance.OnDivideRoad;
            @DivideRoad.canceled -= instance.OnDivideRoad;
            @RemoveRoad.started -= instance.OnRemoveRoad;
            @RemoveRoad.performed -= instance.OnRemoveRoad;
            @RemoveRoad.canceled -= instance.OnRemoveRoad;
            @AbandonBuild.started -= instance.OnAbandonBuild;
            @AbandonBuild.performed -= instance.OnAbandonBuild;
            @AbandonBuild.canceled -= instance.OnAbandonBuild;
            @Elevate.started -= instance.OnElevate;
            @Elevate.performed -= instance.OnElevate;
            @Elevate.canceled -= instance.OnElevate;
            @Lower.started -= instance.OnLower;
            @Lower.performed -= instance.OnLower;
            @Lower.canceled -= instance.OnLower;
            @DragCamera.started -= instance.OnDragCamera;
            @DragCamera.performed -= instance.OnDragCamera;
            @DragCamera.canceled -= instance.OnDragCamera;
            @ToggleParallelBuildMode.started -= instance.OnToggleParallelBuildMode;
            @ToggleParallelBuildMode.performed -= instance.OnToggleParallelBuildMode;
            @ToggleParallelBuildMode.canceled -= instance.OnToggleParallelBuildMode;
        }

        public void RemoveCallbacks(IInGameActions instance)
        {
            if (m_Wrapper.m_InGameActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IInGameActions instance)
        {
            foreach (var item in m_Wrapper.m_InGameActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_InGameActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public InGameActions @InGame => new InGameActions(this);
    public interface IInGameActions
    {
        void OnMoveCamera(InputAction.CallbackContext context);
        void OnBuild(InputAction.CallbackContext context);
        void OnSetLaneWidthTo1(InputAction.CallbackContext context);
        void OnSetLaneWidthTo2(InputAction.CallbackContext context);
        void OnSetLaneWidthTo3(InputAction.CallbackContext context);
        void OnSaveGame(InputAction.CallbackContext context);
        void OnLoadGame(InputAction.CallbackContext context);
        void OnDivideRoad(InputAction.CallbackContext context);
        void OnRemoveRoad(InputAction.CallbackContext context);
        void OnAbandonBuild(InputAction.CallbackContext context);
        void OnElevate(InputAction.CallbackContext context);
        void OnLower(InputAction.CallbackContext context);
        void OnDragCamera(InputAction.CallbackContext context);
        void OnToggleParallelBuildMode(InputAction.CallbackContext context);
    }
}
